# Generated by Django 5.1.1 on 2024-12-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_cart_items_alter_fooditem_image_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
